name: 🐛 Bug Report
description: Report a problem in a lab, notebook, or test file.
title: "[BUG] <brief summary>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below clearly.

  - type: input
    id: lab_task
    attributes:
      label: Lab / Task Affected
      description: e.g. Lab-02 / Task-01
      placeholder: "Lab-02 / Task-01"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: What exactly went wrong?
      placeholder: "Explain the bug or unexpected behavior..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe the issue...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "It should have..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs
      description: Paste any error logs or attach screenshots.
      placeholder: "Error message or image link"
